server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.hhn.studyChat: DEBUG
    org.springframework.web: INFO
  file:
    name: /app/logs/studyChat.log

crawler:
  output:
    dir: /app/collected-content
  max:
    threads: 2

http:
  agent:
    name: StudyChat-Bot
    version: 1.0
    description: StudyChat Crawler für Hochschule Heilbronn
    url: https://www.hs-heilbronn.de
    email: contact@example.com

# Docker-specific configuration - use container names
qdrant:
  host: ${QDRANT_HOST:qdrant}
  port: ${QDRANT_PORT:6334}

openai:
  api:
    key: ${OPENAI_API_KEY:demo}
  model: gpt-4o-mini

use:
  inmemory:
    store: false

langchain:
  chunk-size: 500
  chunk-overlap: 50
  embedding-size: 384

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
  health:
    qdrant:
      enabled: true